Cargo.lock
Cargo.toml
install.sh
src/main.rs

Release v0.0.1.
**Fixes:** N/A

Release v0.0.1

---

Cargo.lock
Cargo.toml
README.md
install.sh
src/main.rs

Release v0.0.2.
**Fixes:** N/A

Release v0.0.2

---

README.md
src/duplicates.rs
src/label.rs

Do some minor copyediting.
**Fixes:** N/A

Do some minor copyediting

---

Cargo.lock
Cargo.toml
install.sh
src/main.rs

Release v0.0.3.
**Fixes:** N/A

Release v0.0.3

---

Cargo.lock
Cargo.toml
install.sh
src/main.rs

Release v0.0.4.
**Fixes:** N/A

Release v0.0.4

---

.gitignore

Make one path in the `.gitignore` more clear.
**Fixes:** N/A

Make one path in the .gitignore more clear

---

LICENSE

Update the copyright year.
**Fixes:** N/A

Update the copyright year

---

Cargo.lock
Cargo.toml
install.sh
src/main.rs

Release v0.0.6.
**Fixes:** N/A

Release v0.0.6

---

README.md
install.sh

Fix an issue with `sudo` in the installation mechanism.
**Fixes:** N/A

Fix an issue with `sudo` in the installation mechanism

---

Cargo.toml
src/citations.rs
src/count.rs
src/duplicates.rs
src/label.rs
src/main.rs
src/walk.rs

Upgrade to Rust 2018.
**Fixes:** N/A

Upgrade to Rust 2018

---

src/main.rs

Make a constant for the path option.
**Fixes:** N/A

Make a constant for the path option

---

.travis.yml
rustfmt.toml
src/citations.rs
src/duplicates.rs
src/label.rs
src/main.rs
src/walk.rs

Add a CI check for formatting.
**Fixes:** N/A

Add a CI check for formatting

---

src/citations.rs
src/label.rs
src/main.rs

Make the subcommand logic more straightforward.
**Fixes:** N/A

Make the subcommand logic more straightforward

---

Cargo.lock
Cargo.toml
install.sh
src/main.rs

Release v0.0.7.
**Fixes:** N/A

Release v0.0.7

---

README.md
src/citations.rs
src/duplicates.rs
src/label.rs
src/main.rs
src/walk.rs

Use `Path`/`PathBuf` where appropriate instead of strings.
**Fixes:** N/A

Use `Path`/`PathBuf` where appropriate

---

.travis.yml
bake.yml

Use [Bake](https://github.com/stepchowfun/bake) for CI.
**Fixes:** N/A

Use Bake for CI

---

install.sh

Wrap the installation script in curly braces.

Wrap the installation script in curly braces

---

Cargo.lock
Cargo.toml
src/main.rs

Release v0.0.8

---

install.sh

Install v0.0.8 by default

---

README.md
src/main.rs

Invoke Clap with better settings.

Invoke Clap with better settings

---

.travis.yml
bake.yml

Pin the Bake version

---

Cargo.lock
Cargo.toml
README.md
bake.yml
src/citations.rs
src/duplicates.rs
src/label.rs
src/main.rs
src/walk.rs

Add a `list-unused` subcommand.

Add a list-unused subcommand

---

src/label.rs
src/main.rs
src/walk.rs

Stream the files rather than requiring them to fit in memory.

Stream the files rather than requiring them to fit in memory

---

src/main.rs
src/walk.rs

Add parallelism. On my laptop, this reduced the time from ~30s to ~8s on a big directory with 29k files.

Add parallelism

---

Cargo.lock
Cargo.toml
src/main.rs

Release v0.1.0

---

.gitignore
.ignore
bake.yml
install.sh

Install v0.1.0 by default and use that version for CI.

Install v0.1.0 by default and use that version for CI

---

README.md
src/walk.rs

Clarify that Tagref ignores symlinks.

Clarify that Tagref ignores symlinks

---

src/label.rs

**There is no user-facing change from this PR.**
Explicitly ignore whitespace in the regexes rather than `trim`ing the resulting matches. That way the entire parsing behavior is described by the regex, rather than having the logic split between the regex and some other part of the code.
I also added a test to make explicit that tags and references are case-sensitive.
@juliahw

Explicitly ignore whitespace in the regexes rather than `trim`ing the resulting matches

---

bake.yml
install.sh

Install v1.0.0 by default and use that version for CI.

Install v1.0.0 by default and use that version for CI

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs

Release v1.1.0

---

bake.yml
install.sh

Install v1.1.0 by default and use that version for CI.

Install v1.1.0 by default and use that version for CI

---

src/main.rs

Fix a typo in a comment

---

.travis.yml

Use Bake v0.4.0 for CI

---

.travis.yml
bake.yml

Use Bake v0.6.0 for CI

---

README.md
bake.yml
src/citations.rs
src/label.rs

Update the bakefile and the installation instructions.

Update the bakefile and the installation instructions

---

.travis.yml

Use Bake v0.7.0 for CI

---

.travis.yml

Use Bake v0.9.0 for CI

---

.travis.yml
bake.yml

Update the Bakefile

---

.travis.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
install.sh
src/main.rs
toast.yml

Release 1.2.0 and switch from Bake to Toast.

Release 1.2.0 and switch from Bake to Toast

---

install.sh
toast.yml

Install v1.2.0 by default and use that version for CI.

Install v1.2.0 by default and use that version for CI

---

.travis.yml

Upgrade Toast to v0.18.0

---

.travis.yml
install.sh

Use `shasum` rather than `sha256sum` for portability.

Use `shasum` rather than `sha256sum` for portability

---

.gitignore
.ignore
README.md
release.sh
rustfmt.toml
src/citations.rs
src/count.rs
src/duplicates.rs
src/label.rs
src/main.rs
src/walk.rs
toast.yml

Modernize the CI

---

.travis.yml

Use Toast v0.21.0

---

.travis.yml
toast.yml

Use Toast v0.27.0 for CI

---

Cargo.toml

Remove unnecessary `default-features` flag from `Cargo.toml`.

Remove unnecessary `default-features` flag from `Cargo.toml`

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs

Disable the `--version` flag in subcommands.

Disable the `--version` flag in subcommands

---

install.sh
release.sh
toast.yml

Install v1.2.1 by default and use that version for CI.

Install v1.2.1 by default and use that version for CI

---

.travis.yml

Upgrade Toast to v0.30.0

---

LICENSE
toast.yml

Upgrade Rust to v1.41.0

---

.github/workflows/ci.yml
README.md

Switch from Travis to GitHub Actions for CI.

Switch from Travis to GitHub Actions for CI

---

.github/workflows/ci.yml

Fix a typo in the GitHub workflow.
**Fixes:** N/A

Fix a typo in the GitHub workflow

---

src/main.rs
src/ref.rs
src/walk.rs
toast.yml

Update Rust and rename a file.
**Fixes:** N/A

Update Rust and rename a file

---

README.md

Update the README in light of the new `--tag-prefix` and `--ref-prefix` features.
**Fixes:** N/A

Update the README in light of the new `--tag-prefix` and `--ref-prefix` features

---

install.sh

Install v1.3.1 by default.
**Fixes:** N/A

Install v1.3.1 by default

---

README.md

Wordsmith the README to hopefully clarify what Tagref does.
cc @jgonera @juliahw
**Fixes:** N/A

Wordsmith the README to hopefully clarify what Tagref does

---

README.md
src/main.rs

Make the help text more consistent.
**Fixes:** N/A

Make the help text more consistent

---

toast.yml

Upgrade Rust to v1.47.0.
**Fixes:** N/A

Upgrade Rust to v1.47.0

---

.github/workflows/ci.yml
CODE_OF_CONDUCT.md
Cargo.toml
LICENSE.md
src/label.rs
src/main.rs
toast.yml

Update this project to be consistent with my other Rust projects.
**Fixes:** N/A

Update this project to be consistent with my other Rust projects

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/walk.rs

Change Tagref to scan hidden files (files that start with `.`). Previously it would skip them.
**Fixes:** N/A

Change Tagref to scan hidden files

---

install.sh

Install v1.3.2 by default.
**Fixes:** N/A

Install v1.3.2 by default

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/walk.rs

Skip over `.git` and `.hg`.
**Fixes:** N/A

Skip over `.git` and `.hg`

---

install.sh

Install v1.3.3 by default.
**Fixes:** N/A

Install v1.3.3 by default

---

CHANGELOG.md
Cargo.lock
Cargo.toml
release.sh

Release v1.4.0.
**Fixes:** N/A

Release v1.4.0

---

install.sh

Install v1.4.0 by default.
**Fixes:** N/A

Install v1.4.0 by default

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/walk.rs

Release v1.4.1.
**Fixes:** N/A

Release v1.4.1

---

install.sh

Install v1.4.1 by default.
**Fixes:** N/A

Install v1.4.1 by default

---

LICENSE.md
toast.yml

Update everything for 2021.
**Fixes:** N/A

Update everything for 2021

---

.github/workflows/ci.yml

Fix the Toast branch name.
**Fixes:** N/A

Fix the Toast branch name

---

toast.yml

Fix an issue with the linter.
**Fixes:** N/A

Fix an issue with the linter

---

src/main.rs

Reorder some lines.
**Fixes:** N/A

Reorder some lines

---

README.md
src/main.rs

Tweak the CLI configuration.
**Fixes:** N/A

Tweak the CLI configuration

---

README.md

Tweak the formatting in the usage info.
**Fixes:** N/A

Tweak the formatting in the usage info

---

README.md

Add a note about Airbnb's usage of Tagref.
**Fixes:** N/A

Add a note about Airbnb's usage of Tagref

---

src/duplicates.rs
src/references.rs
toast.yml

Upgrade Rust to v1.52.1.
**Fixes:** N/A

Upgrade Rust to v1.52.1

---

install.sh

Install v0.5.0 by default.
**Fixes:** N/A

Install v0.5.0 by default

---

.github/workflows/ci.yml
toast.yml

Update Rust to v1.55.0.
**Fixes:** N/A

Update Rust to v1.55.0

---

README.md

Reformat some text in the README.
**Fixes:** N/A

Reformat some text in the README

---

README.md

Remove "extensively" from a sentence, as I can no longer verify or quantify this.
**Fixes:** N/A

Remove "extensively" from a sentence, as I can no longer verify or quantify this

---

.github/workflows/ci.yml
src/main.rs
toast.yml

Upgrade to Rust 1.59.0.
**Fixes:** N/A

Upgrade to Rust 1.59.0

---

.github/workflows/ci.yml
src/duplicates.rs
src/references.rs
toast.yml

Upgrade to Rust 1.62.0.
**Fixes:** N/A

Upgrade to Rust 1.62.0

---

CHANGELOG.md
Cargo.lock
Cargo.toml
src/main.rs

Release v1.6.0.
**Fixes:** N/A

Release v1.6.0

---

install.sh

Install v.6.0 by default.
**Fixes:** N/A

Install v.6.0 by default

---

install.sh

Install v1.7.0 by default.
**Fixes:** N/A

Install v1.7.0 by default

---

src/main.rs

Fixes #168 
I decided to take a stab at this, and looks like you were right, it was pretty easy to get working. I had to feel my way through the `clap` API, let me know if there's anything I can improve on. Also, I'm not super happy with the name `--error`, any suggestions?

Add an --error option to throw an error on unused tags

---

CHANGELOG.md
Cargo.lock
Cargo.toml

Release v1.8.0.
**Fixes:** N/A

Release v1.8.0

---

install.sh

Install v1.8.0 by default.
**Fixes:** N/A

Install v1.8.0 by default

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml

Add support for macOS on Apple silicon.
**Fixes:** N/A

Add support for macOS on Apple silicon

---

install.sh

Release v1.8.1.
**Fixes:** N/A

Release v1.8.1

---

.github/workflows/ci.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
install.sh
toast.yml

Add support for AArch64 GNU Linux.
**Fixes:** N/A

Add support for AArch64 GNU Linux

---

install.sh

Install v1.8.2 by default.
**Fixes:** N/A

Install v1.8.2 by default

---

install.sh

Install v1.8.3 by default.
**Fixes:** N/A

Install v1.8.3 by default

---

README.md

Remove a cringey claim about being "blazing fast" and do some other wordsmithing.
**Fixes:** N/A

Remove a cringey claim about being "blazing fast"

---

MAINTAINERS.md

Update the MAINTAINERS instructions for updating Homebrew.
**Fixes:** N/A

Update the MAINTAINERS instructions for updating Homebrew

---

install.sh

Install v1.8.4 by default.
**Fixes:** N/A

Install v1.8.4 by default

---

.github/workflows/ci.yml
Cargo.lock
src/main.rs
toast.yml

Upgrade to Rust 1.72.0.
**Fixes:** N/A

Upgrade to Rust 1.72.0

---

README.md

Make the README slightly less obnoxious.
**Fixes:** N/A

Make the README slightly less obnoxious

---

README.md

Do some minor wordsmithing on the README.
**Fixes:** N/A

Do some minor wordsmithing on the README

---

.github/workflows/ci.yml
toast.yml

Update Rust to v1.74.0.
**Fixes:** N/A

Update Rust to v1.74.0

---

README.md

Remove unnecessary prose from the README.
**Fixes:** N/A

Remove unnecessary prose from the README

---

.github/workflows/ci.yml
.gitignore
.pre-commit-hooks.yaml
CHANGELOG.md
Cargo.lock
Cargo.toml
MAINTAINERS.md
README.md
toast.yml

Add documentation and a test for the pre-commit configuration.
**Fixes:** N/A

Add documentation and a test for the pre-commit configuration

---

install.sh

Install v1.8.5 by default.
**Fixes:** N/A

Install v1.8.5 by default

---

MAINTAINERS.md
toast.yml

Fix a few typos.
**Fixes:** N/A

Fix a few typos

---

README.md

Reorder things in the README.
**Fixes:** N/A

Reorder things in the README

---

src/duplicates.rs
src/tag_references.rs

Fix a couple of flaky tests.
**Fixes:** N/A

Fix a couple of flaky tests

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
src/main.rs

Do some wordsmithing on the README and the help text.
**Fixes:** N/A

Do some wordsmithing on the README and the help text

---

README.md
install.sh

Install v1.9.1 by default.
**Fixes:** N/A

Install v1.9.1 by default

---

.github/workflows/ci.yml
src/dir_references.rs
src/directive.rs
src/duplicates.rs
src/file_references.rs
src/main.rs
src/tag_references.rs
toast.yml

Update Rust to v1.76.0.
**Fixes:** N/A

Update Rust to v1.76.0

---

README.md

Update the list of known users.
**Fixes:** N/A

Update the list of known users

---

README.md
src/main.rs

Use a better example in the README.
**Fixes:** N/A

Use a better example in the README

---

README.md
install.sh
src/directive.rs
src/main.rs

Install v1.10.0 by default.
**Fixes:** N/A

Install v1.10.0 by default

---

README.md

Remove a broken link from the README.
**Fixes:** N/A

Remove a broken link from the README

---

.github/workflows/ci.yml
Cargo.toml
src/directive.rs
src/walk.rs
toast.yml

Update Rust to v1.87.0.
**Fixes:** N/A

Update Rust to v1.87.0

---

.github/workflows/ci.yml
toast.yml

Update Rust to v1.88.0.
**Fixes:** N/A

Update Rust to v1.88.0
