src/main.rs
Use `entry` and `or_insert` and eliminate an `unwrap`. Thanks @larat7 for the tip!
**Fixes:** N/A
=> Use or_insert

src/citations.rs, src/label.rs, src/main.rs
Use `or_insert_with` instead of `or_insert` for a little more performance. This was another tip from @larat7. :)
I also removed some unnecessary or vestigial comments.
**Fixes:** N/A
=> Use or_insert_with

README.md, install.sh
Allow the installer script to accept a version number and installation prefix. Examples:
```sh
$ curl -LSfs https://raw.githubusercontent.com/stepchowfun/tagref/master/install.sh | sudo sh
$ curl -LSfs https://raw.githubusercontent.com/stepchowfun/tagref/master/install.sh | sudo VERSION=0.0.4 sh
$ curl -LSfs https://raw.githubusercontent.com/stepchowfun/tagref/master/install.sh | sudo PREFIX=/usr/local/bin sh
```
cc @larat7
**Fixes:** N/A
=> Allow the installer script to accept a version number and installation prefix

src/citations.rs, src/label.rs, src/main.rs, src/walk.rs
Previously I was unable to install [Clippy](https://github.com/rust-lang-nursery/rust-clippy), becuase it wouldn't compile against stable or nightly Rust. But I tried again today and it worked. This PR fixes all the warnings that Clippy produced.
Thanks @larat7 for suggesting that I use Clippy. :)
**Fixes:** N/A
=> Fix Clippy warnings

.travis.yml, Cargo.lock, README.md, src/citations.rs, src/duplicates.rs, src/label.rs, src/main.rs
Make list-tags and list-refs subcommands instead of flags. This PR also adds Clippy to the CI checks and addresses the lints.
**Fixes:** N/A
=> Make list-tags and list-refs subcommands instead of flags

install.sh
Try to install without `sudo` first. Some environments don't have `sudo`.
**Fixes:** N/A
=> Try to install without sudo first

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Remove GitHub templates. GitHub has a new mechanism for templates that we can try.
**Fixes:** N/A
=> Remove GitHub templates

Cargo.lock, Cargo.toml, src/label.rs, src/main.rs
Make Tagref faster by pre-compiling regular expressions.
=> Make Tagref faster by pre-compiling regular expressions

Cargo.lock, Cargo.toml, src/main.rs
Release v1.0.0. Tagref is mature:
- There are no known bugs.
- Tagref is feature complete.
- Tagref is fast. All obvious optimizations (e.g., parallelization, precompiling regexes, etc.) have been implemented.
- The code was written thoughtfully, its formatting agrees with `rustfmt`, it passes `clippy`, it passes Tagref itself, and there is a test suite.
- Error messages are clear and use proper punctuation, capitalization, etc.
- There is documentation.
It's time for the version number to reflect that maturity.
@juliahw
=> Release v1.0.0

README.md, src/label.rs, src/main.rs, src/walk.rs
@juliahw had the great idea to support scanning multiple paths. After this change, you can do:
```sh
tagref --path path1 --path path2 ...
```
This is not the same as running Tagref on each of the paths separately:
```sh
tagref --path path1
tagref --path path2
...
```
In the first example, files from `path1` can reference tags in files from `path2`, and vice versa. In the second example, each of the paths must be self-contained with respect to tags and references.
=> Support multiple paths

install.sh
It seems there isn't a portable way to verify checksums. Many distributions don't ship with `shasum`.
This checksum verification step was somewhat superfluous in the sense that if the data become corrupted over the wire, it would fail to decrypt before we even got to the checksum verification step (the file is downloaded via HTTPS). Also, it was never a security measure because the binary and the checksum are downloaded from the same host, so if one is compromised the other might as well be do. So I feel comfortable removing this unnecessary check to make the installation script more portable.
@juliahw
=> Don't check the checksum in the installer script

Cargo.lock, src/main.rs, toast.yml
Upgrade Rust to version 1.39.0.
=> Upgrade Rust to version 1.39.0

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/label.rs, src/main.rs, src/references.rs
Add support for custom prefixes. Now you can write tags like `[mytagprefix:foo]` and reference them with `[myrefprefix:foo]` if you invoke Tagref like `tagref --tag-prefix mytagprefix --ref-prefix myrefprefix`.
cc @juliahw @sharmilajesupaul
**Fixes:** N/A
=> Add support for custom prefixes

install.sh, release.sh
Install v1.3.0 by default. I also fixed some very weird typos in the `release.sh` script.
**Fixes:** N/A
=> Install v1.3.0 by default

CHANGELOG.md, Cargo.lock, Cargo.toml, src/label.rs, src/main.rs
Precompile regexes to improve performance.
Before:
```sh
tagref  8.17s user 3.61s system 96% cpu 12.192 total
```
After:
```sh
tagref  3.43s user 3.49s system 68% cpu 10.104 total
```
These are sample runs, but they are adequately representative of the average of a few runs.
**Fixes:** N/A
=> Precompile regexes to improve performance

README.md
Remove a redundant word from the README. I also took the opportunity to give another sentence more punch.
**Fixes:** N/A
=> Remove a redundant word from the README

README.md
Clarify one of Tagref's guarantees.
**Fixes:** N/A
=> Clarify one of Tagref's guarantees

src/main.rs
Convert build warnings into errors.
**Fixes:** N/A
=> Convert build warnings into errors

src/main.rs
Remove extra trailing commas that were previously needed to satisfy the trailing comma lint check.
**Fixes:** N/A
=> Remove extra trailing commas that were previously needed to satisfy the trailing comma lint check

src/count.rs, src/duplicates.rs, src/main.rs, src/references.rs
Fix new default lints for clippy:
- uninlined_format_args
- write_with_newline
=> Fix clippy lints

Cargo.lock, Cargo.toml, src/label.rs, src/main.rs
A minor change when printing refs/tags and their locations: show them in a table with uniform column widths.
~~Not ready for merge, because I wanted feedback first.~~
- ~~Should this be default or introduce a CLI flag? or environment variable for convenience?~~ It's now default.
- ~~The ref format is changed from [ref:identifier] to identifier but that can be reverted to as it was before~~ Keeping the identifier.
```shell
% target/debug/tagref list-refs
?label?                     ./src/main.rs:48              
cities_nonempty             ./README.md:43                
colorless_tests             ./.github/workflows/ci.yml:62 
colorless_tests             ./.github/workflows/ci.yml:83 
excluded_input_paths        ./.gitignore:1                
format_macros               ./toast.yml:148 …
```
=> Output list-refs results as columns

src/main.rs
The order of the values returned by dimensions_stdout() where swapped, they should be (width, height) but were (height, width) instead. (source: <https://docs.rs/term_size/0.3.2/term_size/fn.dimensions_stdout.html>)
=> Fix invalid term_size width

.pre-commit-hooks.yaml
Make it work with https://pre-commit.com/#rust
Tested by adding
```
- repo: https://github.com/goretkin/tagref
rev: 8592d879ebe809178490aec435f05d85066dc43d
hooks:
- id: tagref
language_version: 1.74.0
```
to my project's `.pre-commit-config.yaml`
(After this PR lands, change to
```
- repo: https://github.com/stepchowfun/tagref
rev: main
hooks:
- id: tagref
language_version: 1.74.0
```
)
=> Add pre-commit.com support

CHANGELOG.md, Cargo.lock, Cargo.toml, README.md, src/directive.rs, src/main.rs
I discovered `tagref` today, when looking for a system inspired from GHC notes. I was delighted and tried it on a code-base where I have been writing notes, but it didn't work! I am not sure why, but let me describe the problem:
* Setup: Here is my sysinfo, as published by `neofetch`:
OS: macOS 14.3.1 23D60 arm64
Host: MacBookAir10,1
Shell: fish 3.7.0
Terminal: tmux
CPU: Apple M1
On this system, `tagref` did not recognize any tags in my code, even when I had tags.
```
─> tagref
0 tags, 0 tag references, 0 file references, and 0 directory references validated in 464 files.
```
The problem seems to be in the capture group used in the regular expressions, which I verified using `rg` and `gsed`:
```
─> rg "\[\s*tag\s*:.*\s*\]"
components/whatsapp/src/ai/salher/whatsapp/core.clj
267:;; ## …
```
=> Simplify pre-compiled regular expressions for sigils

README.md
Compress the README a bit.
**Fixes:** N/A
=> Compress the README a bit

src/main.rs
In case the `--path` option was specified multiple times, it'd consider the subcommand as yet another path value, thereby causing the subcommand to default to `Check`.
Steps to reproduce:
```bash
$ mkdir /tmp/{foo,bar}
$ echo "[tag: hello]" > /tmp/foo/file.txt
$ echo "[ref: hello]" > /tmp/bar/file.txt
$ tagref -p /tmp/foo -p /tmp/bar list-tags
1 tag, 1 tag reference, 0 file references, and 0 directory references validated in 2 files.
```
Notice that it prints the output of check subcommand instead of list-tags. This happens because the default behavior `Args::multiple(true)` in clap (version 2.x) is to allow multiple values per occurrence of the option.
Setting `Args::number_of_values(1)` in coordination with `Args::multiple(true)` fixes it. It allows multiple occurrences of the option …
=> Prevent multiple occurrences of --path from eating up the subcommand

README.md
Clarify the meaning of the paths for file and directory references.
**Fixes:** N/A
=> Clarify the meaning of the paths for file and directory references

README.md
Linkify the known large users.
**Fixes:** N/A
=> Linkify the known large users

README.md
Wordsmith the note about GHC notes.
**Fixes:** N/A
=> Wordsmith the note about GHC notes
